name: ci
on:
  - pull_request
  - push
jobs:
  ci:
    name: ${{matrix.node}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: ${{matrix.node}}
      - run: yarn
      - run: yarn test
    strategy:
      matrix:
        node:
          - lts/dubnium
          - node
